# OpenAI secrets
OPENAI_API_KEY = "sk-proj-11xSBryiYlkG4591wKbJT3BlbkFJxSqk7CZYu6st1lckyNzq"

# Astra DB secrets
ASTRA_API_ENDPOINT = "https://c1c81fa9-633d-4a0c-bbd1-aa2875ec3dd1-us-east-2.apps.astra.datastax.com"
ASTRA_TOKEN = "AstraCS:BColhUruBoRYGfYtbWYPBvHx:aa77a4102ec754130ff7d4925fef08bb3441f454a6196830b5996ea3188fe55b"
